org: tommivayrynen
app: bot_pakedi
service: bot-pakedi-lambda
frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:REGION}
  memorySize: 256 #optional, in MB, default is 1024
  # Timeout for functions (default: 6 seconds).
  # Note: API Gateway has a maximum timeout of 30 seconds
  # OpenAI API might take a while to answer
  timeout: 20
  environment:
    BOT_PUBLIC_KEY: ${env:BOT_PUBLIC_KEY}

functions:
  proxy:
    handler: src/proxy.handler
    events:
      - httpApi: "*"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - sns:Publish
        Resource: "*"
  handler:
    handler: src/botPakedi.handler
    events:
      - sns: ${env:SNS_EVENT_TOPIC}