org: tommivayrynen
app: bot_pakedi
service: bot-pakedi-lambda
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript


provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:REGION}
  memorySize: 128 #optional, in MB, default is 1024
  # Timeout for functions (default: 6 seconds). 
  # Note: API Gateway has a maximum timeout of 30 seconds
  # How long does open API take?
  timeout: 6 
  environment:
    TEST: ${env:TEST} 

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'